PRE = ("Generate an image. The attached photo is the exact product reference sheet for the Indian oral-care brand HABBITS. "
       "Products: Te-Cha Charcoal Mint Toothpaste (matte black tube, vertical white 'Habbits' serif wordmark), Natural Whitening Powder (matte black jar, white tooth logo), "
       "Advance Whitening Serum (slim black pump bottle). Reproduce every product you show exactly as in the reference: same shape, matte black packaging, the 'Habbits' wordmark, the tooth logo, same label layout. "
       "Do not add text to labels that is not in the reference. Do not invent other products or brands. ")
SUF = (" [NO PLATFORM CHROME] Render only the standalone ad creative. No phone status bar, device frame, Sponsored label, captions, like counts or buttons unless explicitly described as part of the design."
       " [EDGE-SAFE] All text and products stay within the central 84% of the canvas, about 8% padding from every edge; nothing touches or runs off an edge."
       " [TEXT FIDELITY] Render exactly the words specified in double quotes, spelled exactly, no extra words, prices or claims anywhere. Inside chat bubbles or notes: plain words only, no emoji, and exactly the number of lines or messages specified.")
REAL = (" PHOTOREALISM: full-frame camera, 35-50mm lens, natural skin texture with pores, real fabric creases, true-to-life light, slight grain. Looks like a real unretouched photograph of real people, not CGI. "
        "Indian subject with natural Indian skin tone. Anatomy must be correct: exactly two arms and two hands, five fingers each. ")
TRIO = "the three products side by side, equal spacing, labels facing camera: the black Te-Cha toothpaste tube, the black Whitening Powder jar, the slim black Whitening Serum pump bottle"
PILL = "a small rounded pill badge in lime #C9F24B with black bold text \"BUY 2 GET 1 FREE\""

SYS = {
'M': " [DESIGN SYSTEM: MINIMAL SWISS] Premium, uncluttered. ONE focal point: the headline is the dominant element, at least 3x larger than any other text. At least 40% empty negative space. No props of any kind. Colour 60-30-10: warm off-white #F4F1EC background, black products, lime #C9F24B accent on the offer pill only. Everything on one centre axis. Soft even studio light, crisp product photography, heavy modern grotesque sans-serif.",
'T': " [DESIGN SYSTEM: BOLD TYPOGRAPHY] Type is the hero: the headline fills about 60% of the canvas, heavy condensed sans-serif, tight leading, set flush left. Products are small (under 20% of the height) in the lower right. Only two colours plus the offer pill. No props, no gradients, no decorations.",
'N': " [DESIGN SYSTEM: NATIVE LO-FI] Must look like something an ordinary person made on their phone, not an advertisement: plain default phone UI typography, no brand styling, no polish, casual real phone-camera photo quality. It should blend into a social feed.",
'F': " [DESIGN SYSTEM: FACE AND GAZE] A real person's face draws attention first; their eye-line points at the product and the offer, not at the camera, so the viewer's eye follows it. Product large and legible. Headline sits in clean empty space away from the face.",
'H': " [DESIGN SYSTEM: PRODUCT HERO CONTRAST] One product or group is visually isolated and different from everything else, so it pops out instantly. Single dramatic light source, deep clean shadows, museum-like emptiness. Minimal text.",
'P': " [DESIGN SYSTEM: PROOF AND DATA] Clean information design: the numbers are the hero. Strict grid, precise alignment, tabular figures, generous spacing, black on warm off-white #F4F1EC with lime #C9F24B used only on the final number or the offer.",
'A': " [DESIGN SYSTEM: RICH ART DIRECTION] Editorial magazine-quality lifestyle photograph, a fully styled real scene with warm natural light and depth. The richness is in the image, not in the text: still one clear message and one headline.",
'U': " [DESIGN SYSTEM: DELIBERATELY UGLY] Intentionally amateur and scrappy, like a rushed homemade post: flat phone flash, slightly crooked framing, marker handwriting or MS Paint style. It must look unpolished, but the headline and the offer must still be large and perfectly legible.",
}


def P_(body, s, real=False):
    return PRE + (REAL if real else "") + "1:1 static ad creative, 1080x1080. " + body + SYS[s] + SUF


P = {}
# C1 One tube
P['C1_M_OneTube'] = P_("Top 35%: headline in huge heavy black #111111 sans-serif, two centred lines: \"ONE TUBE\" / \"WON'T DO IT.\" Directly below, one small grey line: \"Not against 3 chais a day.\" Middle 40%: " + TRIO + ". Bottom: " + PILL + ". That is ALL the text.", 'M')
P['C1_P_OneTube'] = P_("Top 22%: headline in heavy black sans-serif, centred, one line: \"ONE TUBE WON'T DO IT.\" Centre-left 55%: a clean white paper receipt, slightly angled, titled \"THE HABBITS ROUTINE\", with exactly these rows, item left and price right: \"Toothpaste / daily\" \"₹249\"; \"Whitening Powder / 4x a week\" \"₹448\"; \"Whitening Serum / before photos\" \"₹549\"; a thin divider; \"Cheapest one free\" \"-₹249\"; then a bold final row \"YOU PAY\" \"₹997\" with ₹997 on a lime #C9F24B highlight. Right side: " + TRIO + ", in a neat group. That is ALL the text.", 'P')
P['C1_U_OneTube'] = P_("Plain white MS Paint canvas. The three products (black Te-Cha toothpaste, black Whitening Powder jar, black Whitening Serum) look roughly cut out and pasted slightly crooked in a row in the middle. Top: \"ONE TUBE WON'T DO IT\" in big red Comic Sans. Rough red MS Paint arrows point to each product with red Comic Sans labels: \"daily\", \"4x a week\", \"before photos\". A wobbly thick red hand-drawn circle around the toothpaste with red Comic Sans text \"THIS ONE FREE\". Bottom: \"BUY 2 GET 1 FREE\" in big black Comic Sans. That is ALL the text.", 'U')
# C2 won't work in 1 day
P['C2_N_OneDay'] = P_("A phone notes-app page filling the canvas (plain off-white paper background, default system font, a thin yellow accent at the top like a notes app, no status bar). Title in bold black: \"no, it won't work in 1 day\". Then exactly five short lines in regular black text, each on its own line: \"Day 1: black powder. weird.\" / \"Week 1: mouth feels properly clean\" / \"Week 2: chai stains start fading\" / \"Week 4: the photo test\" / \"buy 2 get 1 free so you don't run out halfway\". Bottom right: a small casual phone photo, like an image attached to the note, of the black Whitening Powder jar on a bathroom counter. That is ALL the text.", 'N')
P['C2_T_OneDay'] = P_("Background solid matte black #111111. Headline in huge heavy condensed off-white #F4F1EC sans-serif, flush left, filling the upper 60%: \"NO, IT WON'T\" / \"WORK IN\" / \"1 DAY.\" Under it one small off-white line: \"It takes 4 weeks. The 3rd one's free.\" Lower right, small: " + TRIO + ". Lower left: " + PILL + ". That is ALL the text.", 'T')
P['C2_P_OneDay'] = P_("Top 25%: headline in heavy black sans-serif, centred, two lines: \"NO, IT WON'T\" / \"WORK IN 1 DAY.\" Middle 35%: a clean horizontal 4-step progress chart: four equal columns labelled \"WEEK 1\", \"WEEK 2\", \"WEEK 3\", \"WEEK 4\", with a bar under them that fills progressively from light grey to solid black, ending at WEEK 4 with a lime #C9F24B marker and the label \"3X whiter in 30 days\". Bottom 30%: " + TRIO + ", small, standing alone on the plain background, and " + PILL + " centred below them. Show ONLY the three product containers: no grapefruit, no mint leaves, no charcoal pieces, no paste smears, no flowers, no plate, no serum box, no brush. That is ALL the text.", 'P')
# C3 group photo
P['C3_F_GroupPhoto'] = P_("Evening in a warm Indian cafe. A 24-year-old Indian woman in a casual cotton kurta sits at a wooden table on the right half of the frame, looking down at her phone in one hand (screen not visible to us) with a small amused wince; her gaze and head angle point down-left towards the table where " + TRIO + " stand next to a half-finished glass of cutting chai. Top-left clean wall space: headline in heavy off-white sans-serif, two lines: \"ZOOMED INTO THE\" / \"GROUP PHOTO.\" and a smaller line below: \"Saw every chai I've ever had.\" Bottom-left above the products: " + PILL + ". That is ALL the text.", 'F', real=True)
P['C3_N_GroupPhoto'] = P_("A candid, slightly blurry phone photo of four Indian friends in their twenties laughing together at a house party, warm indoor light, flash, not posed, like a real group photo. Over it, casual white phone-story style text with a thin black outline, top area: \"zoomed into the group photo.\" and on the next line: \"saw every chai i've ever had.\" In the lower right corner, like a sticker, a small clean cut-out of " + TRIO + " with a white rounded label under them in bold black text: \"buy 2 get 1 free\", large and easy to read (label text about as big as the top caption). Drinks in hand are steel glasses of chai, no red plastic cups. That is ALL the text.", 'N', real=True)
P['C3_A_GroupPhoto'] = P_("Top-down editorial flat lay on a warm terracotta-and-cream table at golden hour: two clay kulhad cups of chai, a phone lying face up showing a softly blurred group photo of friends, a few marigold petals, and " + TRIO + " lying neatly in a row as the clear focus. Upper third kept calm and empty of objects for the headline in heavy cream #F4F1EC sans-serif, two lines: \"ZOOMED INTO THE\" / \"GROUP PHOTO.\" with a smaller line: \"Saw every chai I've ever had.\" Bottom centre: " + PILL + ". That is ALL the text.", 'A')
# C4 lemon
P['C4_H_Lemon'] = P_("Background warm off-white #F4F1EC. Top 30%: headline in heavy black sans-serif, centred, two lines: \"STOP PUTTING LEMON\" / \"ON YOUR TEETH.\" and one small grey line: \"Stains off. Without acid, bleach or peroxide.\" Lower 55%, split in two: on the left, a half lemon, a small open box of baking soda and a small bowl of turmeric, all slightly desaturated with a single thin red strike line through the group; on the right, lit with a single warm spotlight so they pop, " + TRIO + ". Bottom centre: " + PILL + ". That is ALL the text.", 'H')
P['C4_T_Lemon'] = P_("Background solid warm lemon yellow #FFE45C. Headline in huge heavy condensed black #111111 sans-serif, flush left, filling the upper 65%: \"STOP\" / \"PUTTING\" / \"LEMON ON\" / \"YOUR TEETH.\" Below it one small black line: \"Stains off. Without acid, bleach or peroxide.\" Lower right, small: " + TRIO + ". Lower left: a small black rounded pill with yellow text \"BUY 2 GET 1 FREE\". That is ALL the text.", 'T')
P['C4_U_Lemon'] = P_("A flat, harsh phone-flash photo of a messy Indian kitchen counter at night: a cut half lemon, a steel spoon, a salt packet. A yellow sticky note is stuck on the lemon, written in thick black marker in capitals: \"STOP PUTTING LEMON ON YOUR TEETH.\" Next to it on the counter, " + TRIO + ", with a second sticky note on the powder jar in black marker: \"use this. buy 2 get 1 free\". Slightly crooked framing. That is ALL the text.", 'U')
# C5 black powder
P['C5_H_BlackPowder'] = P_("Background pure bright white. The black Whitening Powder jar alone, centred, lid off and resting beside it, showing the jet-black powder inside, lit by a single dramatic top light with a deep clean shadow: it is the only dark object on the canvas. Top 28%: headline in heavy black sans-serif, centred, two lines: \"THE BLACK POWDER\" / \"EVERYONE DOUBTS.\" and one small grey line: \"Until they try it.\" Bottom: small black text \"10,000+ customers\" and below it " + PILL + ". That is ALL the text.", 'H')
P['C5_F_BlackPowder'] = P_("A real Indian man around 27 in a plain grey t-shirt in a clean, simple bathroom, framed chest-up on the right side. He holds a toothbrush whose bristles are coated in jet-black powder in one hand and the black Whitening Powder jar (label facing camera) in the other, and looks at the black toothbrush with one eyebrow raised in doubt; his gaze leads to the jar. Left clean wall space: headline in heavy black sans-serif, two lines: \"THE BLACK POWDER\" / \"EVERYONE DOUBTS.\" and a smaller line: \"Until they try it.\" Bottom-left: " + PILL + ". That is ALL the text.", 'F', real=True)
P['C5_T_BlackPowder'] = P_("Background solid matte black #111111. Headline in huge heavy condensed off-white #F4F1EC sans-serif, flush left, filling the upper 60%: \"THE BLACK\" / \"POWDER\" / \"EVERYONE\" / \"DOUBTS.\" Below it one small grey line: \"Until they try it. 10,000+ customers.\" Lower right, small: the black Whitening Powder jar, lid off, with a thin rim light so it separates from the background. Lower left: " + PILL + ". That is ALL the text.", 'T')
# C6 WhatsApp
P['C6_N_WhatsApp'] = P_("A family group chat screen filling the canvas, in the style of a common messaging app: beige doodle-pattern chat background, a simple green top bar showing only the group name \"Sharma Family\" (no phone status bar). Exactly five message bubbles, top to bottom: white bubble from \"Mummy\" containing a casual phone photo of " + TRIO + " on a dining table with the caption \"Beta chai ke daag ke liye ye wala lo\"; white bubble from \"Mummy\": \"3 lo, paise sirf 2 ke\"; white bubble from \"Papa\": \"Ek mera\"; white bubble from \"Didi\": \"Ek mera\"; green bubble on the right from me: \"...\". Bottom centre, overlapping the chat footer: " + PILL + ". That is ALL the text.", 'N')

import os
os.makedirs('C:/cca/habbits/p3', exist_ok=True)
for k, v in P.items():
    open(f'C:/cca/habbits/p3/{k}.txt', 'w', encoding='utf-8').write(v)
print(len(P), {k: len(v) for k, v in P.items()})
