PRE = "Generate an image. The attached photo is the exact product reference (MUFASA MAN OUD deodorant stick). Reproduce the product and its label faithfully. "
SUF = (" [NO PLATFORM CHROME] Render only the standalone ad creative, not a screenshot of how it displays in-feed. No device chrome, Sponsored labels, captions, engagement rows or buttons."
       " [EDGE-SAFE] All text, headlines, table content and the product must fit within the central 84% of the canvas, about 8% padding from every edge. Backgrounds may bleed; text and focal elements may not touch or run off any edge."
       " [TEXT FIDELITY] Plain words only in body text, no emoji or special glyphs mid-sentence. Render exactly the number of rows and items specified, do not invent extra ones.")
MOD = ("Premium Indian men's grooming brand Mufasa Man. Matte black cylindrical deodorant stick with a silver lion-crest emblem, white MUFASA MAN wordmark, tagline BOLD. BRILLIANT. CLASSIC. and OUD label. "
       "Palette: matte black #111111, deep navy #1E2A4A, warm oud amber #B8894A, off-white #F4F1EC. Clean modern sans-serif headlines with an elegant serif accent. Soft directional studio light, warm shadows, smoky oud wood and leather props. Mood: understated masculine luxury. ")
P = {}
P['A2'] = PRE + ("Create a 1:1 social media ad image. DIORAMA: A miniature clay theatre stage. Deep navy velvet clay curtains are being drawn open by two tiny clay stagehands on either side. Centre stage on a small plinth stands the black MUFASA MAN OUD deodorant stick from the reference image, faithful to the real product. Curling up from it, a sculpted ribbon of warm amber smoke made of glazed clay catching the light, with tiny clay pieces of oud wood and amber resin arranged at the base in threes. In the dark wings, three tiny grey clay cartoon stink clouds shrinking away. "
 "LIGHTING: Spotlight 45 degrees from upper-left onto the stick, rest in ambient shadow. Shadow colour navy #1E2A4A at 30% opacity. Highlights warm cream, never pure white. CAMERA: 85mm, eye-level, shallow depth of field, stick sharp, no lens distortion. COMPOSITION: Perfect bilateral symmetry, theatre stage with wings, three depth layers. "
 "TEXTURE: Stick glossy and faithful; smoke ribbon luminous glazed; curtains and stagehands finger-pressed clay; stink clouds rough and dull. COLOR: Neutral dark scene, the amber smoke (#B8894A) is the only saturated element. "
 "TYPOGRAPHY: HEADLINE \"ODOUR GONE. OUD STAYS.\" top third, centred, bold condensed geometric sans-serif (Bebas Neue / Anton style), off-white #F4F1EC, ALL CAPS. CTA \"Smell the difference\" bottom third, centred, medium sans, amber #B8894A, sentence case. FRAMING: 10px solid #111111 border, no vignette. MOOD: A reveal. Premium, theatrical, confident. DO NOT: mannequin figures, floating objects, pure black shadows, decorative fonts, any other text.")
P['A3'] = PRE + ("Create a 1:1 social media ad image. DIORAMA: A miniature clay tailor's wardrobe. A tiny clay Indian man with an expressive happy face is mid-motion pulling on a crisp black shirt, arms raised, the underarm area of the shirt visibly spotless. Behind him, three black shirts hang in a perfect row on a clay rail. On a small clay dresser in the foreground stands the black MUFASA MAN OUD deodorant stick from the reference image, faithful to the real product. A small clay mirror reflects him grinning. "
 "LIGHTING: Golden hour, warm directional light from frame-right, amber-touched edges. Shadow colour navy #1E2A4A at 30% opacity. Highlights warm cream. CAMERA: 35mm, bird's-eye tilt 15 degrees down, deep focus. COMPOSITION: Centred subject framed by the wardrobe doors on both sides, shirts repeating in threes. "
 "TEXTURE: Man and shirts finger-pressed clay; stick glossy and faithful; wardrobe walls flat matte. COLOR: Warm throughout, amber accent glowing; matte black #111111 shirts and stick, navy #1E2A4A walls. "
 "TYPOGRAPHY: HEADLINE \"FINALLY. NO WHITE MARKS.\" top third, centred, bold condensed geometric sans-serif, off-white #F4F1EC, ALL CAPS, with a small line under it \"Rohan, Delhi\" in medium sans. CTA \"Wear black again\" bottom third, centred, amber #B8894A. FRAMING: 10px solid #111111 border. MOOD: Relief and quiet pride. DO NOT: mannequin figures, floating objects, decorative fonts, any other text.")
P['B1'] = PRE + ("1:1 static ad creative, 1080x1080, edge-to-edge. A fake weather-app forecast UI styled as your day on the Mufasa Man Oud Deo Stick. Standalone ad creative. Background deep matte black #111111 with a very subtle warm amber glow at the centre. "
 "Top section (about 22% height): a small muted grey caps label \"TODAY, MUMBAI\", then below a centred bold off-white sans-serif headline in two stacked lines: \"36\u00b0C. 80% Humidity.\" / \"0% Sweat Smell.\" Below the headline, a thin grey hairline divider. "
 "Middle section (about 44% height): a horizontal hourly forecast strip, five evenly spaced columns, each top to bottom: time label (small grey sans), a small minimal vector-style icon in soft amber, a condition label in off-white sans, a smaller subtitle in light grey. "
 "Column 1: \"9 AM\", sun icon, \"Metro Crush\", \"Fresh\". Column 2: \"12 PM\", cloud icon, \"Humid Front\", \"Still fresh\". Column 3: \"3 PM\", thermometer icon, \"Meeting Heat\", \"No odour\". Column 4: \"7 PM\", dumbbell icon, \"Gym Session\", \"Holding\". Column 5: \"10 PM\", moon icon, \"Dinner Date\", \"Smoky oud\". Render icons as simple vector shapes, not emoji. "
 "Lower section (about 30% height): the MUFASA MAN OUD deodorant stick from the reference image with its cap off beside it showing the white balm, centred, premium studio product photography, soft rim light, faithful to the real label. "
 "Bottom (about 4%): small off-white sans text \"Mufasa Man Oud Deo Stick | mufasaman.com\". Modern minimal premium aesthetic." + SUF)
P['B2'] = PRE + ("1:1 static ad creative, 1080x1080, edge-to-edge. A dark-mode comparison ad image. Near-black background #0E0E10 with a subtle radial warm amber #B8894A glow at the centre. Tiny amber plus marks in the four corners. "
 "Top text in chunky off-white sans-serif, stacked two lines centred: \"Your Body Spray\" on line 1, \"Quits By Lunch\" on line 2, where only the word \"Lunch\" is coloured amber #D4A25A. "
 "Below, a row of three rounded-square tiles: left tile dark grey with a simple white outline drawing of a generic aerosol can and caption \"Body Spray\"; middle a small angled amber \"VS\" badge; right tile black with the MUFASA MAN OUD deodorant stick from the reference image and caption \"Mufasa Oud Stick\". "
 "Below the tiles, a dark comparison table with thin grey grid lines. Header row in grey caps: \"WHAT YOU GET\" | \"BODY SPRAY\" | \"OUD STICK\". The OUD STICK column is outlined with a thin amber border. Exactly 5 rows: "
 "\"Scent lasts\" | \"1-2 hours\" | \"All day\"; \"Odour\" | \"Covers it\" | \"Neutralises it\"; \"Alcohol\" | \"Yes\" | \"0%\"; \"Where it goes\" | \"Half in the air\" | \"All on skin\"; \"One pack lasts\" | \"Weeks\" | \"Months\". "
 "Brand column values in amber, others in grey. Labels in regular sans-serif." + SUF)
P['B3'] = PRE + ("1:1 static ad creative, 1080x1080, edge-to-edge. A clean editorial layout on a warm off-white background #F4F1EC. "
 "Top section (about 22% height): centred bold black sans-serif headline in two stacked lines, large: \"SMELL GONE\" / \"BY LUNCH?\" "
 "Middle section (about 34% height): exactly five checklist rows, each a hollow grey square checkbox followed by text in regular black sans-serif: \"Re-spraying in the office washroom\", \"Scent that fades in an hour\", \"Sticky roll-on that never dries\", \"White marks on your black shirt\", \"Buying a deo AND a perfume\". "
 "Lower section (about 30% height): the MUFASA MAN OUD deodorant stick from the reference image with its cap off showing the white balm, a few pieces of dark oud wood beside it, soft natural light, premium product photography, faithful label. "
 "Bottom section (about 14% height): line 1 in bold serif \"ONE SWIPE. OUD ALL DAY.\"; line 2 smaller sans \"Mufasa Man Oud Deo Stick. Alcohol-free, aluminium-free, no white marks. mufasaman.com\". Modern, premium, calm." + SUF)
P['C1'] = "Generate a 1:1 image. " + MOD + ("Use the attached image as brand reference and match the exact product design. Create: a side-by-side comparison divided vertically. Left half: muted grey-blue background. Right half: matte black #111111 background. Centre top: white circle with \"VS\". "
 "Left header: \"BODY SPRAY\" with a generic unbranded grey aerosol can, and a list with red X marks: \"Fades in 1-2 hours\", \"Masks smell, doesn't stop it\", \"Alcohol that stings\", \"Half of it goes in the air\", \"Re-buy every month\". "
 "Right header: \"MUFASA MAN OUD STICK\" with the black Mufasa Man Oud deodorant stick from the reference, and a list with amber check marks: \"Lasts all day\", \"Neutralises odour\", \"0% alcohol, 0% aluminium\", \"Every swipe on skin\", \"One stick lasts months\". MUFASA MAN wordmark bottom right.")
P['C2'] = "Generate a 1:1 image. " + MOD + ("Use the attached image as brand reference and match the exact product design. Create: a static ad on a clean off-white #F4F1EC background. Top centre: large amber #B8894A opening quotation marks. Below: a mixed-weight headline in black: first line in italic serif \"The fragrance is very premium,\", the next line in enormous heavy bold all-caps sans-serif \"BOLD AND CLASSY.\", followed by a smaller sentence-case line \"A proper rich oud smell. And it's a deodorant.\" Closing quotation marks and \"Verified Amazon buyer\" in regular weight. "
 "Left side bottom third: the Mufasa Man Oud deodorant stick at a slight angle, cap off showing the white balm. To the left of the product: a small round badge reading \"0% Alcohol 0% Aluminium\". Right side bottom third: five filled amber stars and bold text \"Oud Deo Stick, 75g\". Bottom edge: small text \"Individual experiences may vary.\"")
P['C3'] = "Generate a 1:1 image. " + MOD + ("Use the attached image as brand reference and match the exact product precisely. Create: a lifestyle product photo on a slightly cluttered Indian office desk, afternoon light through window blinds. Frame slightly off-centre, feels found rather than composed, slight sensor grain. "
 "Centre: the Mufasa Man Oud deodorant stick standing on the desk next to a laptop, a steel tiffin box and a glass of cutting chai, slightly angled. A few paper clips and a pen around the base. Stuck on the product: a yellow square post-it note, slightly crooked, realistic paper texture with a crease, handwritten in thick black marker, imperfect lowercase, four lines: \"stop re-spraying\" / \"in the office loo\" / \"1 swipe at 8am\" / \"still oud at 8pm\". "
 "No logo overlay; brand carried by the packaging. Bottom: small caption text \"mufasaman.com - the deo that smells like perfume\".")
for k, v in P.items():
    open(f'C:/cca/mufasa/p/{k}.txt', 'w', encoding='utf-8').write(v)
print({k: len(v) for k, v in P.items()})
